apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: phzae4klj-go
  janus-idp.io/tekton: phzae4klj-go
  backstage.io/kubernetes-id: phzae4klj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: phzae4klj-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
