apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: phzae4klj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: phzae4klj-go 
  name: phzae4klj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: phzae4klj-go 
